### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/TechnoSMPGaming#1]
Definetly not sus that you and your friend totally wrote all this code in 3 days! Totally like it's not pirated! That's definetly it!
@TechDudie, deny my invite for InsaneChess. And btw, idk how discord.js or nextcord.js works and i shouldnt be talking. I dont have a minecraft account either so im not on TechnoSMP. sorry for my totally useless interuption that i totally sent

**Comment by TechDudie** [comment]
because i had help one of my friends is helping go away
